### ISSUE TITLE
Extra slash in url bypasses rights list

### ISSUE THREAD

**Issue by nathanhollows** [nliautaud/pico-users#14]
Checking rights can be bypassed by putting an extra slash in the URL.

Accessing `https://example.com/hidden/` prompts for password as expected. Accessing `https://example.com//hidden/` allows immediate access

My rights look like this:
```
rights:
    hidden: nathan
    alsohidden: nathan
```
This is on a fresh install of pico cms and this plugin

**Comment by nliautaud** [comment]
Hi, thanks for the report.

It depends on how double slashes should be considered by Pico. It probably should be defined either as a different page (`//` being a subdirectory without name), or dropped and redirected, but not dismissed as it seems to be now.

Anyway I'm not sure about the relevance of this plugin since a larger one have been made : https://github.com/picoauth/picoauth.
