### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by McGun** [nliautaud/pico-users#2]
I get this message when I try to login:
"Warning: Invalid argument supplied for foreach() in /plugins/_pico_users.php on line 175"

Also, I can read a page which I have set to only one specific user.

Best regards.

**Comment by nliautaud** [comment]
The input of `$settings['users']` (see [line 26](https://github.com/nliautaud/pico-users/blob/961621bddbd4f4a89155a2fd97edf216ac70bea5/_pico_users.php#L26)) seems to be invalid. It need to be an associative array. Can you paste the `users` setting from your config file ? Thanks.

**Comment by McGun** [comment]
Sorry for my late reply.
Here is my config code:
```
$settings['users'] = array
(
    'admin' => array(
        'mackan' => '21e1873893e7f04378890ca1b9f8666bdec062f1'
    )
);

$settings['rights'] = array
(
    'testar/' => 'admin',
    'testar/' => 'admin/mackan'
);
```

Also, when I go to the URL example.com/testar
I can se and browse the page perfectly normal, even though I'm not logged in.

**Comment by nliautaud** [comment]
The config is ok, and I can't reproduce the issue here. Is the warning displayed only at login ?
I've done an edit that may be related, you may try again.

About the page rights, there is a difference induced by the trailing slash, see [#rights-management](https://github.com/nliautaud/pico-users/blob/50a734a6f9dd1d4f59efa0c2ab015affce39e389/README.md#rights-management). to preserve ``testar`` and its content, you may use : 

    'testar' => 'admin',
    'testar/' => 'admin'

But depending on what happening with users, that may break the expected behavior anyway.
